export const TIERS = [
  {
    min: 0,
    label: "野生のヤシ酒", en: "Wild Palm Wine",
    shape:  "relative overflow-hidden rounded-xl border",
    bg:     "bg-white",
    border: "border-gray-200",
    ring:   "ring-gray-200",
    bar:    "bg-gray-300",
    badge:  "bg-gray-100 text-gray-500",
    glow:   "",
    ornamentLevel: 0, ornamentColor: "",
    // ── 追加フィールド ──────────────────────────────────────────
    cardInlineBg: "#ffffff",
    barInlineBg:  "linear-gradient(90deg, #d1d5db, #9ca3af)",
    shimmerClass: "",
  },
  {
    min: 5,
    label: "ティール・ジンの輝き", en: "Sapphire Glow",
    shape:  "relative overflow-hidden rounded-2xl border-2",
    bg:     "bg-teal-50",
    border: "border-teal-300",
    ring:   "ring-teal-300",
    bar:    "bg-teal-400",
    badge:  "bg-teal-100 text-teal-700",
    glow:   "shadow-lg shadow-teal-100",
    ornamentLevel: 0, ornamentColor: "",
    cardInlineBg: "linear-gradient(135deg, #f0fdfa 0%, #ccfbf1 100%)",
    barInlineBg:  "linear-gradient(90deg, #14b8a6, #2dd4bf)",
    shimmerClass: "",
  },
  {
    min: 10,
    label: "サファイア・ブルー・キュラソー", en: "Teal Curacao",
    shape:  "relative overflow-hidden rounded-2xl border-2",
    bg:     "bg-blue-50",
    border: "border-blue-400",
    ring:   "ring-blue-400",
    bar:    "bg-blue-400",
    badge:  "bg-blue-100 text-blue-700",
    glow:   "shadow-lg shadow-blue-200",
    ornamentLevel: 1, ornamentColor: "text-blue-300",
    cardInlineBg: "linear-gradient(135deg, #eff6ff 0%, #dbeafe 60%, #eff6ff 100%)",
    barInlineBg:  "linear-gradient(90deg, #2563eb, #60a5fa, #3b82f6)",
    shimmerClass: "",
  },
  {
    min: 20,
    label: "深紫のピノ・ノワール", en: "Deep Violet Pinot",
    shape:  "relative overflow-hidden rounded-2xl border-2 ring-1 ring-offset-2 ring-violet-300 ring-offset-violet-50",
    bg:     "bg-violet-50",
    border: "border-violet-400",
    ring:   "ring-violet-400",
    bar:    "bg-violet-400",
    badge:  "bg-violet-100 text-violet-800",
    glow:   "shadow-xl shadow-violet-200",
    ornamentLevel: 2, ornamentColor: "text-violet-400",
    cardInlineBg: "linear-gradient(135deg, #f5f3ff 0%, #ede9fe 45%, #ddd6fe 100%)",
    barInlineBg:  "linear-gradient(90deg, #6d28d9, #a78bfa, #7c3aed)",
    shimmerClass: "",
  },
  {
    min: 35,
    label: "悠久の琥珀・マデイラ", en: "Amber Madeira",
    shape:  "relative overflow-hidden rounded-2xl border-2 ring-2 ring-offset-2 ring-amber-300 ring-offset-amber-50",
    bg:     "bg-amber-50",
    border: "border-amber-400",
    ring:   "ring-amber-400",
    bar:    "bg-amber-500",
    badge:  "bg-amber-100 text-amber-800",
    glow:   "shadow-xl shadow-amber-200",
    ornamentLevel: 3, ornamentColor: "text-amber-400",
    cardInlineBg: "linear-gradient(135deg, #fffbeb 0%, #fde68a 30%, #fff7ed 65%, #fffbeb 100%)",
    barInlineBg:  "linear-gradient(90deg, #b45309, #f59e0b, #d97706)",
    shimmerClass: "",
  },
  {
    min: 50,
    label: "天上の翠黄・シャルトリューズ", en: "Citrine Chartreuse",
    shape:  "relative overflow-hidden rounded-3xl border-2 ring-2 ring-offset-2 ring-lime-400 ring-offset-lime-50",
    bg:     "bg-lime-50",
    border: "border-lime-500",
    ring:   "ring-lime-500",
    bar:    "bg-lime-500",
    badge:  "bg-lime-100 text-lime-800",
    glow:   "shadow-2xl shadow-lime-200",
    ornamentLevel: 4, ornamentColor: "text-lime-500",
    cardInlineBg: "linear-gradient(135deg, #f7fee7 0%, #d9f99d 35%, #ecfccb 65%, #f0fdf4 100%)",
    barInlineBg:  "linear-gradient(90deg, #4d7c0f, #a3e635, #65a30d)",
    shimmerClass: "",
  },
  {
    min: 75,
    label: "女王のローズ・シャンパーニュ", en: "Rose Champagne",
    shape:  "relative overflow-hidden rounded-3xl border-2 ring-4 ring-offset-2 ring-rose-300 ring-offset-rose-50",
    bg:     "bg-rose-50",
    border: "border-rose-400",
    ring:   "ring-rose-400",
    bar:    "bg-rose-400",
    badge:  "bg-rose-100 text-rose-800",
    glow:   "shadow-2xl shadow-rose-200",
    ornamentLevel: 5, ornamentColor: "text-rose-400",
    cardInlineBg: "linear-gradient(135deg, #fff1f2 0%, #ffe4e6 25%, #fecdd3 55%, #fce7f3 80%, #fff1f2 100%)",
    barInlineBg:  "linear-gradient(90deg, #be123c, #fb7185, #e11d48, #fb7185)",
    shimmerClass: "tier-rose-shimmer",
  },
  {
    min: 100,
    label: "黄金の貴腐（ノーブル・ロット）", en: "Noble Rot Gold",
    shape:  "relative overflow-hidden rounded-3xl border-4 border-double ring-4 ring-offset-4 ring-yellow-400 ring-offset-yellow-50",
    bg:     "bg-gradient-to-br from-yellow-50 via-amber-50 to-yellow-100",
    border: "border-yellow-500",
    ring:   "ring-yellow-500",
    bar:    "bg-yellow-500",
    badge:  "bg-gradient-to-r from-yellow-200 to-amber-200 text-amber-900",
    glow:   "shadow-2xl shadow-yellow-300 tier-noble-glow",
    ornamentLevel: 6, ornamentColor: "text-yellow-500",
    cardInlineBg: "linear-gradient(135deg, #fef9c3 0%, #fde68a 20%, #fffbeb 40%, #fcd34d 55%, #fef9c3 72%, #fde68a 88%, #fffbeb 100%)",
    barInlineBg:  "linear-gradient(90deg, #92400e, #d97706, #fbbf24, #f59e0b, #d97706)",
    shimmerClass: "tier-noble-shimmer",
  },
] as const;

export function getTier(count: number) {
  for (let i = TIERS.length - 1; i >= 0; i--) {
    if (count >= TIERS[i].min) return { ...TIERS[i], index: i };
  }
  return { ...TIERS[0], index: 0 };
}
